### ISSUE TITLE
Create side bar

### ISSUE THREAD

**Issue by mcscoder** [mcscoder/html-css-practice-2#5]
Side bar components: [here](https://github.com/mcscoder/html-css-practice-2/blob/preview/side-bar/Sidebar.jpg)
Side bar view: [here](https://github.com/mcscoder/html-css-practice-2/blob/preview/side-bar/Sidebar-view.jpg)

**Comment by duongpham-agilityio** [comment]
I don't understand issues for you. Please raise detail
